### ISSUE TITLE
Support short form of Authors and Tags?

### ISSUE THREAD

**Issue by grantwinney** [grantwinney/GhostSharp#10]
There's a [short form](https://docs.ghost.org/api/admin/#tags-and-authors) for tags and authors, but supporting it in C# is more complicated than in JavaScript, [where the types are made up and the fields don't matter](https://www.youtube.com/watch?v=1gl__LLKMIs).

> You can link tags and authors to any post you create in the same request body, using either short or long form to identify linked resources.
> 
> Short form uses a single string to identify a tag or author resource. Tags are identified by name and authors are identified by email address:
> 
> ```json
> {
>     "posts": [{
>         "title": "My test post",
>         "tags": ["Getting Started", "Tag Example"],
>         "authors": ["example@ghost.org", "test@ghost.org"]
>     }]
> }
> ```

I didn't implement it yet, but if there was a strong reason to, then I'd do something about it... maybe.

**Comment by devdog66** [comment]
Can I assist in this portion? I am looking to get Author information out of Posts. Excellent project and NuGet package. I want to use this for a site I may put out someday.

**Comment by devdog66** [comment]
I figured out my issue. I wasn't adding the option for Authors via the Query Params. In case anyone else has issues with pulling Author info here is how to add that.

```csharp
var postQueryParams = new PostQueryParams();
postQueryParams.IncludeAuthors = true;
ghostPosts = ghost.GetPosts(postQueryParams).Posts
    .OrderByDescending(x => x.UpdatedAt)
    .ToList();
```

**Comment by grantwinney** [comment]
Glad you got it working for your needs!

I haven't revisited this in quite some time... probably could use some TLC. It was just a personal challenge, I don't really use it for anything or I'd be better about upkeep. 😅
