### ISSUE TITLE
update for the admin api - is themes a valid endpoint?

### ISSUE THREAD

**Issue by grantwinney** [grantwinney/GhostSharp#17]
Looks like "themes" is now stable - uploading, activating.

https://ghost.org/docs/api/v3/admin/#endpoints

Unfortunately, they provide no examples for it, so it's "stable" but doesn't seem to be supported yet. ?? _**(Same as of Sept 21)**_

* https://github.com/HexRweb/ghost-deploy/blob/2.0.0/actions/activate-theme.js
* https://github.com/HexRweb/ghost-deploy/tree/2.0.0/actions
* https://forum.ghost.org/t/uploading-a-theme-via-the-admin-api/12249

**Comment by naz** [comment]
Hey @grantwinney it is a valid stable endpoint and for best reference you could use Ghost's [Admin-API SDK implementation](https://github.com/TryGhost/Ghost-SDK/blob/a3a58ca1a96962a182fd91d48be797428da1afb7/packages/admin-api/lib/index.js#L244-L265 ) :wink: 

Good point about lack of example docs. Will raise this question internally and might improve in the future :crossed_fingers:

**Comment by grantwinney** [comment]
Thanks @naz I'll check it out! Hopefully that didn't come off snarky or anything, the docs that are there are great... I kinda forget these are public and just use them for personal notes, heh.

**Comment by naz** [comment]
Not snarky at all! It's very cool to see people using the API. Sometimes comments like this remind about little holes that need patching :raised_hands:

**Comment by grantwinney** [comment]
Implemented the themes endpoint.
