### ISSUE TITLE
The byte conversion code in the auth flow can now be replaced by a built-in method

### ISSUE THREAD

**Issue by jessehouwing** [grantwinney/GhostSharp#30]
This snippet of code:

https://github.com/grantwinney/GhostSharp/blob/45d181209d07d467edfc941f14cfcd3f6024538b/GhostSharp/Extensions.cs#L61-L68

Is now natively supported in .NET 5 and up through:

```
Convert.FromHexString()
```

See:
https://learn.microsoft.com/en-us/dotnet/api/system.convert.fromhexstring?view=net-6.0&WT.mc_id=DOP-MVP-5001511

**Comment by grantwinney** [comment]
Thanks for the heads up @jessehouwing! I made the replacement.
